version: "2"
services:
  main-app:
    image: main-app
    environment:
      NODE_ENV: 'production'
      MONGOURL: 'mongodb://mongo/bus-tracker'
    ports:
      - "80:3000"
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
      # The volume to hold database files.
      - mongo-data:/data/db
    restart: unless-stopped
volumes:
  mongo-data:
    driver: local
